server.port=4000
spring.application.name=timetracker
app.base-url=${BASE_URL}
# Database settings
spring.datasource.url=jdbc:h2:file:./data/timetracker;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

# Telegram bot settings
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot-username=${TELEGRAM_BOT_USERNAME}